/** Deterministic, synthetic Nameplate portfolio for local development/tests. */
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
const BASE = new Date('2026-08-01T12:00:00.000Z');
const ORG = '00000000-0000-4000-8000-000000000001';
function id(n: number): string { return `00000000-0000-4000-8000-${n.toString(16).padStart(12, '0')}`; }
function ago(days: number): Date { return new Date(BASE.getTime() - days * 86_400_000); }
function npid(n: number): string { const chars = '0123456789ABCDEFGHJKMNPQRSTVWXYZ'; let body = ''; for (let i = n; body.length < 8; i = Math.floor(i / chars.length)) body = chars[i % chars.length] + body; return `NP-${body}`; }

async function main() {
  await prisma.organization.create({ data: { id: ORG, name: 'Sonoran Portfolio Management', slug: 'sonoran-portfolio-management', plan: 'pilot', timezone: 'America/Phoenix', currency: 'USD', settings: { replace_threshold_pct: 60, replace_approval_limit_usd: 400, require_photo_on_service: true } } });
  const users = [
    ['00000000-0000-4000-8000-000000000010', 'owner@sonoran.example', 'Portfolio Owner'], ['00000000-0000-4000-8000-000000000011', 'marcus@sonoran.example', 'Marcus Chen'], ['00000000-0000-4000-8000-000000000012', 'elena@sonoran.example', 'Elena Ruiz'], ['00000000-0000-4000-8000-000000000013', 'morales@sonoran.example', 'J. Morales'],
  ] as const;
  await prisma.user.createMany({ data: users.map(([userId, email, fullName]) => ({ id: userId, email, fullName, status: 'active' as const })) });
  const memberships = [
    { id: id(100), orgId: ORG, userId: users[0][0], role: 'owner' as const, employmentType: 'employee', status: 'active' as const }, { id: id(101), orgId: ORG, userId: users[1][0], role: 'technician' as const, employmentType: 'employee', hourlyLaborRate: 28.5, status: 'active' as const }, { id: id(102), orgId: ORG, userId: users[2][0], role: 'lead_tech' as const, employmentType: 'employee', hourlyLaborRate: 34, status: 'active' as const }, { id: id(103), orgId: ORG, userId: users[3][0], role: 'technician' as const, employmentType: 'employee', hourlyLaborRate: 32, status: 'active' as const },
  ];
  await prisma.membership.createMany({ data: memberships });
  const categoryDefs = [['washer', 'Washer', 132, 650], ['dryer', 'Dryer', 144, 550], ['range', 'Range / Oven', 180, 700], ['refrigerator', 'Refrigerator', 156, 900], ['dishwasher', 'Dishwasher', 120, 480], ['water_heater', 'Water Heater', 120, 1100], ['hvac_air_handler', 'HVAC Air Handler', 216, 3200], ['microwave', 'Microwave', 108, 220], ['thermostat', 'Smart Thermostat', 84, 180]] as const;
  await prisma.assetCategory.createMany({ data: categoryDefs.map(([key, displayName, life, cost], i) => ({ id: id(200 + i), key, displayName, defaultUsefulLifeMonths: life, defaultReplacementCost: cost })) });
  const modelDefs = categoryDefs.map(([key, displayName, life, cost], i) => ({ id: id(250 + i), manufacturer: ['Whirlpool', 'GE', 'Frigidaire', 'Rheem', 'Carrier'][i % 5], modelNumber: `NP-${key.toUpperCase()}-${i + 1}`, categoryId: id(200 + i), displayName: `${displayName} Standard`, typicalReplacementCost: cost, expectedLifeMonths: life, verificationStatus: 'verified' }));
  await prisma.assetModel.createMany({ data: modelDefs });
  const properties = [{ id: id(300), name: 'Copper Ridge Apartments', code: 'CR-01', city: 'Tucson', state: 'AZ', postalCode: '85712', unitCountDeclared: 80, yearBuilt: 1998 }, { id: id(301), name: 'Desert Willow Commons', code: 'DW-02', city: 'Phoenix', state: 'AZ', postalCode: '85021', unitCountDeclared: 72, yearBuilt: 2005 }, { id: id(302), name: 'Saguaro Vista Apartments', code: 'SV-03', city: 'Mesa', state: 'AZ', postalCode: '85210', unitCountDeclared: 68, yearBuilt: 1989 }];
  await prisma.property.createMany({ data: properties.map((p) => ({ ...p, orgId: ORG, addressLine1: `${p.name} Main Office`, country: 'US', status: 'active' as const })) });
  const units: { id: string; propertyId: string; buildingId: string; label: string }[] = [];
  for (let p = 0, offset = 0; p < properties.length; p += 1) { const buildingId = id(350 + p); await prisma.building.create({ data: { id: buildingId, orgId: ORG, propertyId: properties[p].id, name: 'Main', floors: 4 } }); for (let u = 0; u < properties[p].unitCountDeclared; u += 1) units.push({ id: id(400 + offset + u), propertyId: properties[p].id, buildingId, label: `${100 + u}` }); offset += properties[p].unitCountDeclared; }
  await prisma.unit.createMany({ data: units.map((u, i) => ({ ...u, orgId: ORG, floor: (i % 4) + 1, bedrooms: i % 3 === 0 ? 1 : 2, bathrooms: 1, squareFeet: 650 + (i % 5) * 40, occupancyStatus: i % 11 === 0 ? 'vacant' : 'occupied' })) });
  await prisma.device.createMany({ data: [0, 1, 2].map((i) => ({ id: id(500 + i), orgId: ORG, userId: users[i + 1][0], platform: i === 1 ? 'android' as const : 'ios' as const, model: i === 1 ? 'Pixel 9' : 'iPhone 16', osVersion: '18.5', appVersion: '0.1.0' })) });
  await prisma.storageLocation.createMany({ data: properties.map((p, i) => ({ id: id(520 + i), orgId: ORG, propertyId: p.id, name: `Shop — ${p.code}`, kind: 'shop' as const })) });
  await prisma.vendor.createMany({ data: [{ id: id(530), orgId: ORG, name: 'Sonoran Appliance Repair', kind: 'appliance_repair' as const, hourlyRate: 95 }, { id: id(531), orgId: ORG, name: 'Desert HVAC Services', kind: 'hvac' as const, hourlyRate: 125 }] });
  const assets = Array.from({ length: 900 }, (_, i) => { const unit = units[i % units.length]; const category = i % categoryDefs.length; const status = i % 97 === 0 ? 'unaccounted_for' as const : i % 41 === 0 ? 'needs_repair' as const : i % 53 === 0 ? 'in_repair' as const : 'active' as const; return { id: id(1000 + i), orgId: ORG, npid: npid(i + 1), categoryId: id(200 + category), assetModelId: id(250 + category), manufacturerRaw: modelDefs[category].manufacturer, modelRaw: modelDefs[category].modelNumber, serialNumber: `SN-${String(i + 1).padStart(7, '0')}`, serialConfidence: 'scanned' as const, currentLocationType: 'unit' as const, currentUnitId: unit.id, currentPropertyId: unit.propertyId, currentLocationSince: ago(30 + (i % 900)), currentLocationConfirmedAt: status === 'unaccounted_for' ? ago(220) : ago(i % 45), status, condition: status === 'needs_repair' || status === 'in_repair' ? 'poor' as const : 'good' as const, acquisitionType: 'new_purchase', installDate: ago(30 + (i % 900)), installDateConfidence: 'known', purchaseCost: categoryDefs[category][3], expectedLifeMonths: categoryDefs[category][2] }; });
  await prisma.asset.createMany({ data: assets });
  await prisma.assetLocation.createMany({ data: assets.map((a, i) => ({ id: id(3000 + i), orgId: ORG, assetId: a.id, locationType: 'unit' as const, unitId: a.currentUnitId, propertyId: a.currentPropertyId, fromTs: a.currentLocationSince, moveReason: 'initial_install' as const, movementKind: 'recorded' as const, confirmationMethod: 'qr_scan' as const, occurredAt: a.currentLocationSince, deviceId: id(500 + (i % 3)) })) });
  await prisma.assetIdentifierScan.createMany({ data: assets.slice(0, 300).map((a, i) => ({ id: id(4000 + i), orgId: ORG, rawCode: a.npid, codeType: 'npid' as const, resolvedAssetId: a.id, resolution: 'resolved' as const, scannedBy: memberships[(i % 3) + 1].id, deviceId: id(500 + (i % 3)), expectedPropertyId: a.currentPropertyId, actualPropertyId: a.currentPropertyId, occurredAt: ago(i % 30) })) });
  const workOrders = Array.from({ length: 120 }, (_, i) => { const a = assets[(i * 7) % assets.length]; const u = units[(i * 7) % units.length]; return { id: id(5000 + i), orgId: ORG, propertyId: u.propertyId, number: 1001 + i, unitId: u.id, assetId: a.id, title: i % 3 === 0 ? 'Routine appliance repair' : 'Inspection follow-up', description: 'Deterministic demo work order.', source: i % 2 ? 'technician' as const : 'inspection' as const, priority: i % 13 === 0 ? 'urgent' as const : 'standard' as const, status: i % 9 === 0 ? 'completed' as const : i % 4 === 0 ? 'in_progress' as const : 'open' as const, assignedTo: memberships[(i % 3) + 1].id, requestedAction: 'repair' as const, completedAt: i % 9 === 0 ? ago(i % 20) : undefined, resolution: i % 9 === 0 ? 'repaired' as const : undefined, occurredAt: ago(i % 60) }; });
  await prisma.workOrder.createMany({ data: workOrders });
  const events = Array.from({ length: 540 }, (_, i) => { const a = assets[(i * 13) % assets.length]; const u = units[(i * 13) % units.length]; return { id: id(6000 + i), orgId: ORG, assetId: a.id, workOrderId: workOrders[i % workOrders.length].id, unitId: u.id, propertyId: u.propertyId, technicianId: memberships[(i % 3) + 1].id, eventType: i % 5 === 0 ? 'inspection' as const : i % 7 === 0 ? 'part_replacement' as const : 'repair' as const, findings: 'Portfolio service visit (deterministic seed).', symptomCodes: i % 4 === 0 ? ['noisy'] : [], resolutionCode: i % 8 === 0 ? 'part_replaced' as const : 'fixed' as const, conditionBefore: 'fair' as const, conditionAfter: 'good' as const, laborMinutes: 20 + (i % 50), laborRate: i % 3 === 0 ? 28.5 : 34, partsCost: i % 5 === 0 ? 24 : 0, costBorneBy: 'owner' as const, occurredAt: ago(i % 365), deviceId: id(500 + (i % 3)), createdBy: users[(i % 3) + 1][0] }; });
  await prisma.serviceEvent.createMany({ data: events });
  const partCatalogs = Array.from({ length: 12 }, (_, i) => ({ id: id(7000 + i), manufacturer: 'Nameplate OEM', partNumber: `NP-PART-${i + 1}`, name: `Replacement component ${i + 1}`, componentType: ['pump', 'motor', 'control_board', 'filter'][i % 4] as 'pump' | 'motor' | 'control_board' | 'filter' }));
  await prisma.partCatalog.createMany({ data: partCatalogs });
  const parts = Array.from({ length: 60 }, (_, i) => ({ id: id(7100 + i), orgId: ORG, partCatalogId: partCatalogs[i % partCatalogs.length].id, label: `Seed part ${i + 1}`, componentType: partCatalogs[i % partCatalogs.length].componentType, origin: i % 5 === 0 ? 'salvaged' as const : 'new_purchase' as const, sourceAssetId: i % 5 === 0 ? assets[i].id : undefined, sourceServiceEventId: i % 5 === 0 ? events[i].id : undefined, salvagedAt: i % 5 === 0 ? ago(i) : undefined, salvagedBy: i % 5 === 0 ? memberships[2].id : undefined, condition: i % 5 === 0 ? 'tested_good' as const : 'new' as const, status: i % 4 === 0 ? 'installed' as const : 'in_stock' as const, installedInAssetId: i % 4 === 0 ? assets[(i + 1) % assets.length].id : undefined, acquisitionCost: i % 5 === 0 ? 0 : 35 + i }));
  await prisma.part.createMany({ data: parts });
  await prisma.partUsage.createMany({ data: parts.map((p, i) => ({ id: id(7200 + i), orgId: ORG, serviceEventId: events[i].id, assetId: assets[(i + 1) % assets.length].id, partId: p.id, partCatalogId: p.partCatalogId, action: 'installed', quantity: 1, unitCost: p.acquisitionCost, costSource: p.origin === 'salvaged' ? 'zero_salvaged' : 'actual', occurredAt: events[i].occurredAt })) });
  const turns = Array.from({ length: 30 }, (_, i) => { const u = units[(i * 7) % units.length]; return { id: id(8000 + i), orgId: ORG, propertyId: u.propertyId, unitId: u.id, type: i % 2 ? 'move_out' as const : 'annual_inspection' as const, status: i % 3 === 0 ? 'completed' as const : 'in_progress' as const, scheduledFor: ago(i), startedAt: ago(i + 1), completedAt: i % 3 === 0 ? ago(i) : undefined, performedBy: memberships[(i % 3) + 1].id, itemsTotal: 4, itemsPresent: 3, itemsMissing: 1, occurredAt: ago(i + 1) }; });
  await prisma.turn.createMany({ data: turns });
  await prisma.turnItem.createMany({ data: turns.flatMap((t, i) => [0, 1, 2, 3].map((k) => ({ id: id(8100 + i * 4 + k), orgId: ORG, turnId: t.id, assetId: assets[(i * 11 + k) % assets.length].id, expectedCategoryId: id(200 + ((i + k) % categoryDefs.length)), finding: k === 3 ? 'missing' as const : 'present_ok' as const, condition: k === 3 ? 'poor' as const : 'good' as const, decision: k === 3 ? 'investigate' as const : 'none' as const, verifiedByScan: k !== 3, occurredAt: t.occurredAt }))) });
  const media = Array.from({ length: 30 }, (_, i) => ({ id: id(9000 + i), orgId: ORG, storageKey: `org/${ORG}/property/${assets[i].currentPropertyId}/asset-${i + 1}.jpg`, mimeType: 'image/jpeg', bytes: 120_000 + i, width: 1600, height: 1200, sha256: `seed-sha-${String(i).padStart(3, '0')}`, uploadedBy: users[(i % 3) + 1][0] }));
  await prisma.media.createMany({ data: media });
  await prisma.mediaAttachment.createMany({ data: media.map((m, i) => ({ id: id(9050 + i), orgId: ORG, mediaId: m.id, entityType: 'asset', entityId: assets[i].id, role: i % 5 === 0 ? 'nameplate' as const : 'general' as const, createdBy: users[(i % 3) + 1][0] })) });
  await prisma.reconciliationFlag.createMany({ data: assets.slice(0, 12).map((a, i) => ({ id: id(9200 + i), orgId: ORG, entityType: 'asset', entityId: a.id, kind: 'duplicate_asset_suspected' as const, detail: { source: 'deterministic_seed', index: i } })) });
  await prisma.syncOp.createMany({ data: Array.from({ length: 50 }, (_, i) => ({ opId: id(9300 + i), orgId: ORG, deviceId: id(500 + (i % 3)), userId: users[(i % 3) + 1][0], entityType: 'asset', entityId: assets[i].id, opType: 'create', status: i % 10 === 0 ? 'duplicate' as const : 'applied' as const })) });
  await prisma.auditLog.createMany({ data: Array.from({ length: 100 }, (_, i) => ({ id: id(9400 + i), orgId: ORG, actorUserId: users[(i % 3) + 1][0], actorRole: 'technician' as const, action: 'seed.create', entityType: 'asset', entityId: assets[i].id, after: { source: 'deterministic_seed' }, occurredAt: ago(i % 90) })) });
  await prisma.metricSnapshot.createMany({ data: properties.flatMap((p, i) => [0, 1, 2].map((month) => ({ id: id(9600 + i * 3 + month), orgId: ORG, scopeType: 'property' as const, scopeId: p.id, periodStart: new Date(`2026-${String(month + 5).padStart(2, '0')}-01T00:00:00Z`), periodGrain: 'month' as const, definitionVersion: 1, metrics: { asset_count: 300 - i * 25, service_events: 180 - month * 10, cost: 12500 + i * 450 } }))) });
  console.log(`Seed complete: org=${ORG}; properties=${properties.length}; units=${units.length}; assets=${assets.length}; events=${events.length}; parts=${parts.length}; turns=${turns.length}`);
}
main().catch((error) => { console.error(error); process.exitCode = 1; }).finally(() => prisma.$disconnect());
